### ISSUE TITLE
 Question regarding the future of Syntax::Highlight::Engine::Simple::Perl

### ISSUE THREAD

**Issue by kentfredric** [jamadam/Syntax-Highlight-Engine-Simple-Perl#1]
Hi there, I'm writing on behalf of Gentoo who presently ship Syntax::Highlight::Engine::Simple::Perl

It appears Syntax::Highlight::Engine::Simple::Perl has gone from CPAN, and its not clear if this is an accident, or if it intends to end-of-life the module in some way.

If vanishing from CPAN is merely accidental oversight, this can be rectified easily.

However, if you no longer wish to maintain the module, it may be opportune to either
mark it for adoption, or ship a release with deprecation notices.

NeilB Has some good guides on both:

- [Marking modules as 'available for adoption'](http://neilb.org/2013/08/07/adoptme.html)
- [Marking a distribution as deprecated](http://neilb.org/2015/01/17/deprecated-metadata.html)

Gentoo would also appreciate any feedback you can offer in this regard to feed our decisions if we wish to continue shipping it.

Thanks.

**Comment by jamadam** [comment]
I removed the module from CPAN intentionally.
Next time I remove modules I would follow right deprecation process.

Thanks.

**Comment by akhuettel** [comment]
@jamadam I'm using the module; would it be possible that I get Pause co-maintainership so I can revive it / take over? My Pause id is AKHUETTEL.

**Comment by jamadam** [comment]
I'm happy to hear that.
I've just added you to co-maintainer of the modules.

> Added AKHUETTEL to co-maintainers of Syntax::Highlight::Engine::Simple.
> Added AKHUETTEL to co-maintainers of Syntax::Highlight::Engine::Simple::HTML.
> Added AKHUETTEL to co-maintainers of Syntax::Highlight::Engine::Simple::Perl.

**Comment by akhuettel** [comment]
Thanks!!! (in case you're curious, it's used to build the API documentation on www.labmeasurement.de)
